### ISSUE TITLE
registerUnusedFoodTest implemented incorrectly

### ISSUE THREAD

**Issue by fabianscode** [LadnerJonas/PGdP-Tests-WS21-22#21]
Homework Number (example: W06H01):

PinguFoodLogisticsTest.java line 47:

wrong assumption about wasted food, statistic shall not be set to zero after clearing orderBook.
Right would be:
"Bisher konnten 15 Tiere mit einem Gesamtgewicht von 2373g nicht verwertet werden.
Claudia und Karl-Heinz ist dadurch ein Profit von 35595PD entgangen."

**Comment by LadnerJonas** [comment]
I do not think that any food is wasted when using AmountOrders.

> Claudia und Karl-Heinz wollen den Mix aus PinguFood immer so groß wie möglich halten, weshalb sie **außer bei AmountOrder** immer zufälliges PinguFood verschicken. **Bei AmountOrder erfüllen sie erst den vollständigen Bedarf an Anchovie, dann an Crustacean und schließlich an Sardine.**

**Comment by fabianscode** [comment]
It is, when it is not edible.

**Comment by LadnerJonas** [comment]
Yeah sure, but as we do not use the "randomly" generated food, I would expect the manually created items to be edible.

**Comment by fabianscode** [comment]
Well no, the generated food can also be non-edible.
![image](https://user-images.githubusercontent.com/33459250/144271851-3052f1c6-bb6a-4aee-abd6-0444996074c9.png)
As you can see, there can also be anchovies with age 0.

**Comment by LadnerJonas** [comment]
Yeah true.
Maybe i am missing your point, but i do not see where random food is used until line 47. **Nevermind maybe my own code is wrong**
```
  @Test
  void registerUnusedFoodTest() {
    PinguFoodLogistics pfl1 = new PinguFoodLogistics(BigDecimal.valueOf(5), BigDecimal.valueOf(10), BigDecimal.valueOf(15));
    pfl1.printWasteStatistics();

    assertTrue(baos.toString().contains("Bisher konnten 0 Tiere mit einem Gesamtgewicht von 0g nicht verwertet werden.\n" +
            "Claudia und Karl-Heinz ist dadurch ein Profit von 0PD entgangen."));

    pfl1.acceptNewOrder(new AmountOrder(1, 2, 3)); // no random food here
    pfl1.clearOrderBook();
    PrepareConsole();
    pfl1.printWasteStatistics();

    //assertEquals("", baos.toString());
    assertTrue(baos.toString().contains("Bisher konnten 0 Tiere mit einem Gesamtgewicht von 0g nicht verwertet werden.\n" +
            "Claudia und Karl-Heinz ist dadurch ein Profit von 0PD entgangen."));
```

**Comment by fabianscode** [comment]
The orders are fulfilled inside clearOrderBook(), which itself uses the generateAnchive() method.#
Btw. thanks for the repo saved me a lot of time already ;)!

**Comment by LadnerJonas** [comment]
Yeah i see that now. But i will just ask on zulip as i do not think the instruction is clear. 😴 💤

**Comment by LadnerJonas** [comment]
Currently waiting for a response, but in case you are right: Your values are correct aswell 👍🏻

**Comment by LadnerJonas** [comment]
Yeah you are right! 🎉 Please excuse my stubbornness
