### ISSUE TITLE
toString TradeOrder

### ISSUE THREAD

**Issue by BoehmFabian** [LadnerJonas/PGdP-Tests-WS21-22#22]
Homework Number (example: W06H01):

Citation of the homework instruction:
toString: TradeOrder: Die⎵Bestellung(Einzeln)⎵hat⎵ein⎵Gesamtgewicht⎵von⎵<currentWeight>g⎵und⎵kostet⎵<totalCost>PD.

Der Wert eines PinguFood-Objekts berechnet sich durch weight*ppg

Additional Information:
Ich habe das so verstanden, dass totalCost nicht die Kosten pro Gramm sind, wie es in den Tests suggeriert wird, sondern der Preis der ganzen Bestellung, also für 200g mit einem Preis von 2, dann 400PD.

Englisch:
I understood it to mean that totalCost is not the cost per gram, as suggested in the tests, but the price of the entire order, i.e. for 200g with a price of 2, then 400PD.

edit: Der Wert eines PinguFood-Objekts berechnet sich durch weight*ppg

**Comment by BoehmFabian** [comment]
I think my 200PD should be right:

org.opentest4j.AssertionFailedError: 
Expected :Die Bestellung(Zielgewicht: 100g) hat ein Gesamtgewicht von 200g und kostet 1PD.
Actual   :Die Bestellung(Zielgewicht: 100g) hat ein Gesamtgewicht von 200g und kostet 200PD.

**Comment by LadnerJonas** [comment]
I think this [Zulip post](https://zulip.in.tum.de/#narrow/stream/846-PGdP-W06H01--.20Saleuine.20Grosshandel/topic/Bedeutung.20von.20Cost/near/369317) does explain it well.

Thus, I do not think this test has to be changed. I am not allowed to reveal the solution in the testcase, see the readme file what is allowed and what is not.

Please consider submitting your next issue with a line number of the mistake.

**Comment by BoehmFabian** [comment]
I noticed, that in supplyorder I have as Parameter priceperGramm, while you probably calculate the price beforehand and give the complete price as parameter
