### ISSUE TITLE
LinkedDocumentCollectionTest

### ISSUE THREAD

**Issue by YannickWiest** [LadnerJonas/PGdP-Tests-WS21-22#26]
Homework Number W0701

line 109. 
Meiner Meinung nach sollte size 5 und nicht 4 sein. Wir haben vor line 108 3 LinkedDocuments und 1 DummyLinked(Adresse abc) in der Sammlung. Allerdings entfernt die add Methode keine Dummy Elemente? Zumindest kann ich das der Aufgabenstellung nicht entnehmen. Folglich sollte also in der Collection einfach ein LinkedDocument eingefügt werden, welches die gleiche Addresse wie das DummyElement hat.

**Comment by LadnerJonas** [comment]
Zwei Dokumente mit derselben Adresse sind soweit ich informiert bin nicht erlaubt. Meines wissens testet das sogar ein public Test.

**Comment by YannickWiest** [comment]
Okay danke. Ich habe nochmal die gesamte Aufgabenstellung gelesen und habe diesen Satz hier in der Beschreibung von updateOutgoing gefunden:
" Das Dummy-Element soll am Ende nicht mehr in der Collection enthalten sein. "
Ich hatte das falsch interpretiert und nur für die Unterkollektions, nicht aber für die Hauptcollection implementiert. Durch den fix ist dann natürlich doc0 in line 108 schon enthalten und darf nicht mehr geaddet werde.

**Comment by LadnerJonas** [comment]
Also passt alles?

**Comment by YannickWiest** [comment]
Ja jetzt passt alles. Sorry wegen der kurzzeitigen Verwirrung

**Comment by YannickWiest** [comment]
Und Danke für das Repository <3
