### ISSUE TITLE
Fälschlicherweise werden 2 leeren Zeilen nach Ausgabe erwartet 

### ISSUE THREAD

**Issue by Pekikii** [LadnerJonas/PGdP-Tests-WS21-22#3]
UnitTests W02H02, MarketEndDayPropertiesTest:
`Assert.assertEquals("Der Laden der Saleuine Claudia und Karl-Heinz hat am 2. Tag 85.0PD eingenommen."
				+ System.lineSeparator() + "Dafür wurden 1 Krustentiere, 2 Sardellen und 3 Sardinen verkauft."
				+ System.lineSeparator() + "Insgesamt hat der Laden 255.0PD eingenommen.\n" + System.lineSeparator(),
				outputStreamCaptor.toString().substring(0, (outputStreamCaptor.toString()).length() - 2));`

Nach dem '\n' kommt noch ein lineseparator und demnach werden 2 leere Zeilen nach der Ausgabe erwartet, auch wenn in der Aufgabenstellung steht, dass man nur eine haben sollte.

**Comment by LadnerJonas** [comment]
Please try to pull the newest changes from the repository. This error should be fixed already. Currently the code in the test is:
```java
// Assert
// note: this test can fail, even if the strings are equal. But as long as the strings are equal, this failed test can be ignored.
Assert.assertEquals(
 "Der Laden der Saleuine Claudia und Karl-Heinz hat am 2. Tag 85.0PD eingenommen." + System.lineSeparator() +
 "Dafür wurden 1 Krustentiere, 2 Sardellen und 3 Sardinen verkauft." + System.lineSeparator() +
 "Insgesamt hat der Laden 255.0PD eingenommen." + System.lineSeparator(), // no more \n here
 outputStreamCaptor.toString().substring(0, (outputStreamCaptor.toString()).length() - 2));
```
