### ISSUE TITLE
Change assessment of insert()

### ISSUE THREAD

**Issue by gonsoos** [LadnerJonas/PGdP-Tests-WS21-22#38]
Homework Number W09H01

Citation of the homework instruction:
`insert()` Falls ein gleiches Tupel bereits vorhanden ist, wird das übergebene Tupel verworfen. Es soll das Tupel zurückgegeben werden, welches letztendlich im Pool gespeichert ist.

Additional Information:
If I understand `assertEquals()` correctly, it assesses the equality of the given tuples. For that, it uses our implementation of `tuple.equals(other)`. What we want though, is an assessment of identity.

This should fail, but does not:
`assertEquals(tuple0Duplicate, pool0.insert(tuple0Duplicate));`

I suggest, we change the test according to this example:
```java
assertEquals(tuple0, pool0.insert(tuple0Duplicate)); //old

/* assertEquals(expected, test of identity) */
assertEquals(true, pool0.insert(tuple0Duplicate) == tuple0);
assertEquals(false, pool0.insert(tuple0Duplicate) == tuple0Duplicate);
```

**Comment by LadnerJonas** [comment]
Yeah this is a mistake 🏅. Can you create a pull request with these changes?

**Comment by gonsoos** [comment]
I'll try :)

**Comment by LadnerJonas** [comment]
`assertTrue(pool0.insert(tuple0Duplicate) == tuple0);` 
`assertFalse(pool0.insert(tuple0Duplicate) == tuple0Duplicate);`
is probably a more readable solution
