### ISSUE TITLE
Check if Hashset is still intact

### ISSUE THREAD

**Issue by dorianim** [LadnerJonas/PGdP-Tests-WS21-22#41]
Over here, you refill the hashset:

https://github.com/LadnerJonas/PGdP-Tests-WS21-22/blob/7ee37c6f9fe96d0dfadabb61c9eae19ecc6f2985/W09H01/src/test/pgdp/hashset/TupleHashSetTest.java#L418

But shouldn't the elements remain in there?

**Comment by LadnerJonas** [comment]
Yeah that is correct, i fixed it by adding another assert statement
