### ISSUE TITLE
W12H01 test, getComputeThreadCounter

### ISSUE THREAD

**Issue by rastko2045** [LadnerJonas/PGdP-Tests-WS21-22#45]
W12H01 tests:

Is it possible that the tests don't consider the following scenario? https://zulip.in.tum.de/#narrow/stream/893-PGdP-W12H01--.20Parallel.20PinguMath/topic/.E2.9C.94.20ComputeThreadCounter
It seems like testMinDim, testMultithreadingAddition, and testMultithreadingMultiplication expect the getComputerThreadCounter to be 4/8, but it's possible to have 5/9 if a thread has been started as described in the Zulip post. 

Sorry if this has been mentioned somewhere else, and thanks for the tests :)

**Comment by LadnerJonas** [comment]
Yeah of course, there are multiple solutions to a given problem. But the more generic you write a test, the more errors can be hidden. 

But yeah, i did not think about this test "edge case". But I will not fix the test, because otherwise some other errors are hidden.

Thanks 🏅

**Comment by LadnerJonas** [comment]
Please keep this "Issue" open, so other students can easily find this conversation.
