### ISSUE TITLE
W03H01 - Warum null als Datum?

### ISSUE THREAD

**Issue by EweLo** [LadnerJonas/PGdP-Tests-WS21-22#9]
Hi, ich verstehe nicht warum beim `AuthorTest` bei `testEquals()` beim letzten Testfall **null** für `birthday` angegeben wird. Das führt doch normalerweise zu einer NullPointerException.
```java
assertFalse(AUTHOR.equals(new Author("Max", "Mustermann", "Pinguinstraße 1",
                "max.mustermann@example.de", null)));
```
In der Angabe wird jedoch nirgends der Fall beschrieben, dass `birthday` (oder ein anderer Parameter) **null** ist, warum wird er dann hier auf so ein Fall getestet? Oder hab ich was falsch verstanden?

LG

**Comment by LadnerJonas** [comment]
@paulzhng: Ich hatte bezüglich diesem Test schon einige Anfragen. Könntest du bitte den entsprechenden Satz in der Angabe zitieren der diesen Test benötigt. Falls der Satz nicht vorhanden ist, schreib mir nochmal oder erstell selbst den Pull Request mit dem entfernten Test. Dankeschön 👍

**Comment by paulzhng** [comment]
Hi, ich weiß nicht, ob das von der ÜL so gefordert ist, aber normalerweise werden bei `equals()`-Aufrufen, falls das Argument (bzw. jetzt ein Objektattribut) `null` ist, immer `false` zurückgegeben (bzw. `true`, falls das zu vergleichende Objekt auch `null` ist), anstelle einer `NullPointerException` zu werden. 

Hier der Javadoc für `Object#equals(Object)`: https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#equals(java.lang.Object)

Selbstverständlich kann man diesen Test auch komplett auslassen - jedoch hatte ich den für mich selber noch drinnen gehabt.

**Comment by LadnerJonas** [comment]
Natürlich ist @paulzhng's Einwand für fortgeschrittene Entwickler valide. Aber da Exception und insbesondere Zugriffe auf null-Elemente noch nicht besprochen wurden, kann das meiner Meinung nach nicht von der Aufgabe gefordert werden.
Ich werd den Test mal mit Verweis hierrauf auskommentieren.
